/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business_logic.Customer;
import Business_logic.CarRentalSystem;
import Business_logic.CustomerTableModel;

import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.TableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Shazam
 */
public class CustomerFrame extends javax.swing.JFrame {
    private CustomerTableModel customerTableModel;
    private TableRowSorter<CustomerTableModel> customerTableSorter;


    CarRentalFrame carRentalFrame;
    CarRentalSystem system;
    List<Customer> customers;

    //private CustomerTableModel customerTableModel;
    //private TableRowSorter<CustomerTableModel> customerTableSorter;

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame(CarRentalSystem system, List<Customer> customers) {
        this.customers = customers;
        this.system = system;
          
        customerTableModel = new CustomerTableModel(customers);
        customerTableSorter = new TableRowSorter<>(customerTableModel);

        initComponents();

        jTable1.setRowSorter(customerTableSorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchBar = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        RentCarButton = new javax.swing.JButton();
        Rented_CarsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        RentCarButton.setText("Rent Car");
        RentCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentCarButtonActionPerformed(evt);
            }
        });

        Rented_CarsButton.setText("Rented Car");
        Rented_CarsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rented_CarsButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(customerTableModel);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RentCarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Rented_CarsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SearchButton)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rented_CarsButton)
                    .addComponent(RentCarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RentCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentCarButtonActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please selecte a customer. ");
            return;
        }
        this.carRentalFrame = new CarRentalFrame(customerTableModel.getCustomer(jTable1.getSelectedRow()), 0, system); 
        this.carRentalFrame.setVisible(true);
        createCustomerDetailsFrame(0);

        this.carRentalFrame.setVisible(true);
    }//GEN-LAST:event_RentCarButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        RowFilter<TableModel, Object> rf = RowFilter.regexFilter("(?i).*" + SearchBar.getText(), 0, 1, 2);
        customerTableSorter.setRowFilter(rf);
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void Rented_CarsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rented_CarsButtonActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please selecte a customer. ");
            return;
        }
        this.carRentalFrame = new CarRentalFrame(customerTableModel.getCustomer(jTable1.getSelectedRow()), 1, system); 

        this.carRentalFrame.setVisible(true);
        createCustomerDetailsFrame(1);

    }//GEN-LAST:event_Rented_CarsButtonActionPerformed
    
    private void createCustomerDetailsFrame(int index){
        if(jTable1.getSelectedRow() == -1){
            
           JOptionPane.showMessageDialog(this, "Please select a user.", "Please select a user." ,JOptionPane.INFORMATION_MESSAGE);
           return;
        }
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RentCarButton;
    private javax.swing.JButton Rented_CarsButton;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton SearchButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
